apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: admin
    openshift.io/sa.scc.mcs: s0:c10,c5
    openshift.io/sa.scc.supplemental-groups: 1000100000/10000
    openshift.io/sa.scc.uid-range: 1000100000/10000
  creationTimestamp: null
  name: demoproject
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
