apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: alerts-tls
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1537531130
  creationTimestamp: null
  labels:
    name: prometheus
  name: alerts
spec:
  ports:
  - name: prometheus
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
