apiVersion: v1
kind: Service
metadata:
  annotations:
    oprometheus.io/scheme: https
    oprometheus.io/scrape: "true"
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-tls
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1537531130
  creationTimestamp: null
  labels:
    name: prometheus
  name: prometheus
spec:
  ports:
  - name: prometheus
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
