apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: Prometheus
    openshift.io/display-name: ""
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c10,c0
    openshift.io/sa.scc.supplemental-groups: 1000090000/10000
    openshift.io/sa.scc.uid-range: 1000090000/10000
  creationTimestamp: null
  name: openshift-metrics
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
