apiVersion: v1
groupNames:
- system:authenticated
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: basic-users
roleRef:
  name: basic-user
subjects:
- kind: SystemGroup
  name: system:authenticated
userNames: null
