apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cluster-reader
roleRef:
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: management-admin
  namespace: management-infra
userNames:
- system:serviceaccount:management-infra:management-admin
