apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cluster-admin-0
roleRef:
  name: cluster-admin
subjects:
- kind: User
  name: admin
userNames:
- admin
