apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cluster-reader-2
roleRef:
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: openshift-metrics
userNames:
- system:serviceaccount:openshift-metrics:prometheus
