apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular"},"name":"hawkular-namespace-watcher","namespace":""},"roleRef":{"kind":"ClusterRole","name":"hawkular-metrics"},"subjects":[{"kind":"ServiceAccount","name":"hawkular","namespace":"openshift-infra"}]}
  creationTimestamp: null
  labels:
    metrics-infra: hawkular
  name: hawkular-namespace-watcher
roleRef:
  name: hawkular-metrics
subjects:
- kind: ServiceAccount
  name: hawkular
  namespace: openshift-infra
userNames:
- system:serviceaccount:openshift-infra:hawkular
