apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"metrics-infra":"heapster"},"name":"heapster-cluster-reader","namespace":""},"roleRef":{"kind":"ClusterRole","name":"cluster-reader"},"subjects":[{"kind":"ServiceAccount","name":"heapster","namespace":"openshift-infra"}]}
  creationTimestamp: null
  labels:
    metrics-infra: heapster
  name: heapster-cluster-reader
roleRef:
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: openshift-infra
userNames:
- system:serviceaccount:openshift-infra:heapster
