apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: rolebinding-reader
roleRef:
  name: rolebinding-reader
subjects:
- kind: ServiceAccount
  name: aggregated-logging-elasticsearch
  namespace: logging
userNames:
- system:serviceaccount:logging:aggregated-logging-elasticsearch
