apiVersion: v1
groupNames:
- system:authenticated
- system:unauthenticated
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: self-access-reviewers
roleRef:
  name: self-access-reviewer
subjects:
- kind: SystemGroup
  name: system:authenticated
- kind: SystemGroup
  name: system:unauthenticated
userNames: null
