apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:openshift:controller:serviceaccount-pull-secrets-controller
roleRef:
  name: system:openshift:controller:serviceaccount-pull-secrets-controller
subjects:
- kind: ServiceAccount
  name: serviceaccount-pull-secrets-controller
  namespace: openshift-infra
userNames:
- system:serviceaccount:openshift-infra:serviceaccount-pull-secrets-controller
