apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:openshift:controller:template-service-broker
roleRef:
  name: system:openshift:controller:template-service-broker
subjects:
- kind: ServiceAccount
  name: template-service-broker
  namespace: openshift-infra
userNames:
- system:serviceaccount:openshift-infra:template-service-broker
