apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:openshift:controller:image-trigger-controller
roleRef:
  name: system:openshift:controller:image-trigger-controller
subjects:
- kind: ServiceAccount
  name: image-trigger-controller
  namespace: openshift-infra
userNames:
- system:serviceaccount:openshift-infra:image-trigger-controller
