apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:endpoint-controller
roleRef:
  name: system:controller:endpoint-controller
subjects:
- kind: ServiceAccount
  name: endpoint-controller
  namespace: kube-system
userNames:
- system:serviceaccount:kube-system:endpoint-controller
