apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-scheduler
roleRef:
  name: system:kube-scheduler
subjects:
- kind: SystemUser
  name: system:kube-scheduler
userNames:
- system:kube-scheduler
