apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:pod-garbage-collector
roleRef:
  name: system:controller:pod-garbage-collector
subjects:
- kind: ServiceAccount
  name: pod-garbage-collector
  namespace: kube-system
userNames:
- system:serviceaccount:kube-system:pod-garbage-collector
