apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:horizontal-pod-autoscaler
roleRef:
  name: system:controller:horizontal-pod-autoscaler
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: openshift-infra
userNames:
- system:serviceaccount:kube-system:horizontal-pod-autoscaler
- system:serviceaccount:openshift-infra:horizontal-pod-autoscaler
