apiVersion: v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: view
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: prometheus-reader
  namespace: openshift-metrics
userNames:
- system:serviceaccount:openshift-metrics:prometheus-reader
