apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"metrics-infra":"support"},"name":"heapster","namespace":"openshift-infra"},"secrets":[{"name":"heapster-secrets"},{"name":"hawkular-metrics-certs"},{"name":"hawkular-metrics-account"}]}
  creationTimestamp: null
  labels:
    metrics-infra: support
  name: heapster
secrets:
- name: heapster-secrets
- name: hawkular-metrics-certs
- name: hawkular-metrics-account
