apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: .NET Core Builder Images
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:29Z
  creationTimestamp: null
  generation: 2
  name: dotnet
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run .NET Core 1.0 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/1.0/README.md.
      iconClass: icon-dotnet
      openshift.io/display-name: .NET Core 1.0
      sampleContextDir: app
      sampleRef: dotnetcore-1.0
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex.git
      supports: dotnet:1.0,dotnet
      tags: builder,.net,dotnet,dotnetcore,rh-dotnetcore10
      version: "1.0"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/dotnet:1.0
    generation: 2
    importPolicy: {}
    name: "1.0"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run .NET Core 1.1 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/1.1/README.md.
      iconClass: icon-dotnet
      openshift.io/display-name: .NET Core 1.1
      sampleContextDir: app
      sampleRef: dotnetcore-1.1
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex.git
      supports: dotnet:1.1,dotnet
      tags: builder,.net,dotnet,dotnetcore,rh-dotnetcore11
      version: "1.1"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/dotnet:1.1
    generation: 2
    importPolicy: {}
    name: "1.1"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run .NET Core 2.0 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0/build/README.md.
      iconClass: icon-dotnet
      openshift.io/display-name: .NET Core 2.0
      sampleContextDir: app
      sampleRef: dotnetcore-2.0
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex.git
      supports: dotnet:2.0,dotnet
      tags: builder,.net,dotnet,dotnetcore,rh-dotnet20
      version: "2.0"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/dotnet:2.0
    generation: 2
    importPolicy: {}
    name: "2.0"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and run .NET Core applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0/build/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of .NET Core available on OpenShift, including major versions updates.
      iconClass: icon-dotnet
      openshift.io/display-name: .NET Core (Latest)
      sampleContextDir: app
      sampleRef: dotnetcore-2.0
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex.git
      supports: dotnet
      tags: builder,.net,dotnet,dotnetcore
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/dotnet:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
