apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:56Z
  creationTimestamp: null
  generation: 2
  name: fis-karaf-openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: JBoss Fuse Integration Services 1.0 Karaf S2I images.
      iconClass: icon-jboss
      supports: jboss-fuse:6.2.1,java:8,xpaas:1.2
      tags: builder,jboss-fuse,java,karaf,xpaas,hidden
      version: "1.0"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/fis-karaf-openshift:1.0
    generation: 2
    importPolicy: {}
    name: "1.0"
    referencePolicy:
      type: Source
  - annotations:
      description: JBoss Fuse Integration Services 2.0 Karaf S2I images.
      iconClass: icon-jboss
      supports: jboss-fuse:6.3.0,java:8,xpaas:1.2
      tags: builder,jboss-fuse,java,karaf,xpaas
      version: "2.0"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/fis-karaf-openshift:2.0
    generation: 2
    importPolicy: {}
    name: "2.0"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
