apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Apache HTTP Server (httpd)
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:11Z
  creationTimestamp: null
  generation: 2
  name: httpd
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and serve static content via Apache HTTP Server (httpd) 2.4
        on RHEL 7. For more information about using this builder image, including
        OpenShift considerations, see https://github.com/sclorg/httpd-container/blob/master/2.4/README.md.
      iconClass: icon-apache
      openshift.io/display-name: Apache HTTP Server 2.4
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/httpd-ex.git
      supports: httpd
      tags: builder,httpd
      version: "2.4"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/httpd:2.4
    generation: 2
    importPolicy: {}
    name: "2.4"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and serve static content via Apache HTTP Server (httpd) on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/httpd-container/blob/master/2.4/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Httpd available on OpenShift, including major versions updates.
      iconClass: icon-apache
      openshift.io/display-name: Apache HTTP Server (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/httpd-ex.git
      supports: httpd
      tags: builder,httpd
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/httpd:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
