apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat OpenJDK 8
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:05:03Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.14
  creationTimestamp: null
  generation: 2
  name: java
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,java
      tags: builder,java,openjdk
      version: "8"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/java:8
    generation: 2
    importPolicy: {}
    name: "8"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,java
      tags: builder,java,openjdk
      version: latest
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/java:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
