apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat JBoss EAP 7.0
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:59Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.14
  creationTimestamp: null
  generation: 2
  name: jboss-eap70-openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: JBoss EAP 7.0 S2I images.
      iconClass: icon-eap
      openshift.io/display-name: Red Hat JBoss EAP 7.0
      sampleContextDir: kitchensink
      sampleRef: 7.0.0.GA
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:7.0,javaee:7,java:8
      tags: builder,eap,javaee,java,jboss,hidden
      version: "1.3"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jboss-eap70-openshift:1.3
    generation: 2
    importPolicy: {}
    name: "1.3"
    referencePolicy:
      type: Source
  - annotations:
      description: JBoss EAP 7.0 S2I images.
      iconClass: icon-eap
      openshift.io/display-name: Red Hat JBoss EAP 7.0
      sampleContextDir: kitchensink
      sampleRef: 7.0.0.GA
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:7.0,javaee:7,java:8
      tags: builder,eap,javaee,java,jboss,hidden
      version: "1.4"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jboss-eap70-openshift:1.4
    generation: 2
    importPolicy: {}
    name: "1.4"
    referencePolicy:
      type: Source
  - annotations:
      description: JBoss EAP 7.0 S2I images.
      iconClass: icon-eap
      openshift.io/display-name: Red Hat JBoss EAP 7.0
      sampleContextDir: kitchensink
      sampleRef: 7.0.0.GA
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:7.0,javaee:7,java:8
      tags: builder,eap,javaee,java,jboss,hidden
      version: "1.5"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jboss-eap70-openshift:1.5
    generation: 2
    importPolicy: {}
    name: "1.5"
    referencePolicy:
      type: Source
  - annotations:
      description: JBoss EAP 7.0 S2I images.
      iconClass: icon-eap
      openshift.io/display-name: Red Hat JBoss EAP 7.0
      sampleContextDir: kitchensink
      sampleRef: 7.0.0.GA
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:7.0,javaee:7,java:8
      tags: builder,eap,javaee,java,jboss,hidden
      version: "1.6"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jboss-eap70-openshift:1.6
    generation: 2
    importPolicy: {}
    name: "1.6"
    referencePolicy:
      type: Source
  - annotations:
      description: JBoss EAP 7.0 S2I images.
      iconClass: icon-eap
      openshift.io/display-name: Red Hat JBoss EAP 7.0
      sampleContextDir: kitchensink
      sampleRef: 7.0.0.GA
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:7.0,javaee:7,java:8
      tags: builder,eap,javaee,java,jboss,hidden
      version: "1.7"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jboss-eap70-openshift:1.7
    generation: 2
    importPolicy: {}
    name: "1.7"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
