apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Jenkins
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:27Z
  creationTimestamp: null
  generation: 2
  name: jenkins
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Provides a Jenkins 1.X server on RHEL 7. For more information about
        using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.
      iconClass: icon-jenkins
      openshift.io/display-name: Jenkins 1.X
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: hidden,jenkins
      version: 1.x
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jenkins:1
    generation: 2
    importPolicy: {}
    name: "1"
    referencePolicy:
      type: Source
  - annotations:
      description: Provides a Jenkins 2.X server on RHEL 7. For more information about
        using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.
      iconClass: icon-jenkins
      openshift.io/display-name: Jenkins 2.X
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: jenkins
      version: 2.x
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jenkins:2
    generation: 2
    importPolicy: {}
    name: "2"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Provides a Jenkins server on RHEL 7. For more information about using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Jenkins available on OpenShift, including major versions updates.
      iconClass: icon-jenkins
      openshift.io/display-name: Jenkins (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: jenkins
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/jenkins:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
