apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Nginx HTTP server and a reverse proxy (nginx)
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:23Z
  creationTimestamp: null
  generation: 2
  name: nginx
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and serve static content via Nginx HTTP server and a reverse
        proxy (nginx) on RHEL 7. For more information about using this builder image,
        including OpenShift considerations, see https://github.com/sclorg/nginx-container/blob/master/1.10/README.md.
      iconClass: icon-nginx
      openshift.io/display-name: Nginx HTTP server and a reverse proxy 1.10
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nginx-ex.git
      supports: nginx
      tags: builder,nginx
      version: "1.10"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/nginx:1.10
    generation: 2
    importPolicy: {}
    name: "1.10"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and serve static content via Nginx HTTP server and a reverse
        proxy (nginx) on RHEL 7. For more information about using this builder image,
        including OpenShift considerations, see https://github.com/sclorg/nginx-container/blob/master/1.12/README.md.
      iconClass: icon-nginx
      openshift.io/display-name: Nginx HTTP server and a reverse proxy 1.12
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nginx-ex.git
      supports: nginx
      tags: builder,nginx
      version: "1.12"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/nginx:1.12
    generation: 2
    importPolicy: {}
    name: "1.12"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and serve static content via Nginx HTTP server and a reverse
        proxy (nginx) on RHEL 7. For more information about using this builder image,
        including OpenShift considerations, see https://github.com/sclorg/nginx-container/blob/master/1.8/README.md.
      iconClass: icon-nginx
      openshift.io/display-name: Nginx HTTP server and a reverse proxy 1.8
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nginx-ex.git
      supports: nginx
      tags: builder,nginx
      version: "1.8"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/nginx:1.8
    generation: 2
    importPolicy: {}
    name: "1.8"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and serve static content via Nginx HTTP server and a reverse proxy (nginx) on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/nginx-container/blob/master/1.12/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Nginx available on OpenShift, including major versions updates.
      iconClass: icon-nginx
      openshift.io/display-name: Nginx HTTP server and a reverse proxy (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nginx-ex.git
      supports: nginx
      tags: builder,nginx
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/nginx:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
