apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: PHP
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:18Z
  creationTimestamp: null
  generation: 2
  name: php
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run PHP 5.5 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/5.5/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 5.5
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:5.5,php
      tags: hidden,builder,php
      version: "5.5"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/php:5.5
    generation: 2
    importPolicy: {}
    name: "5.5"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP 5.6 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/5.6/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 5.6
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:5.6,php
      tags: builder,php
      version: "5.6"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/php:5.6
    generation: 2
    importPolicy: {}
    name: "5.6"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP 7.0 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/7.0/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 7.0
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:7.0,php
      tags: builder,php
      version: "7.0"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/php:7.0
    generation: 2
    importPolicy: {}
    name: "7.0"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP 7.1 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/7.1/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 7.1
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:7.1,php
      tags: builder,php
      version: "7.1"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/php:7.1
    generation: 2
    importPolicy: {}
    name: "7.1"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and run PHP applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/7.1/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of PHP available on OpenShift, including major versions updates.
      iconClass: icon-php
      openshift.io/display-name: PHP (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php
      tags: builder,php
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/php:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
