apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: PostgreSQL
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:25Z
  creationTimestamp: null
  generation: 2
  name: postgresql
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Provides a PostgreSQL 9.2 database on RHEL 7. For more information
        about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/tree/master/9.2/README.md.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL 9.2
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: hidden,postgresql
      version: "9.2"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/postgresql:9.2
    generation: 2
    importPolicy: {}
    name: "9.2"
    referencePolicy:
      type: Source
  - annotations:
      description: Provides a PostgreSQL 9.4 database on RHEL 7. For more information
        about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/tree/master/9.4/README.md.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL 9.4
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
      version: "9.4"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/postgresql:9.4
    generation: 2
    importPolicy: {}
    name: "9.4"
    referencePolicy:
      type: Source
  - annotations:
      description: Provides a PostgreSQL 9.5 database on RHEL 7. For more information
        about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/tree/master/9.5/README.md.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL 9.5
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
      version: "9.5"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/postgresql:9.5
    generation: 2
    importPolicy: {}
    name: "9.5"
    referencePolicy:
      type: Source
  - annotations:
      description: Provides a PostgreSQL 9.6 database on RHEL 7. For more information
        about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/tree/master/9.6/README.md.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL (Ephemeral) 9.6
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
      version: "9.6"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/postgresql:9.6
    generation: 2
    importPolicy: {}
    name: "9.6"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Provides a PostgreSQL database on RHEL 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/tree/master/9.6/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of PostgreSQL available on OpenShift, including major versions updates.
      iconClass: icon-postgresql
      openshift.io/display-name: PostgreSQL (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: database,postgresql
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/postgresql:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
