apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: Red Hat SSO 7.0
    openshift.io/display-name: Red Hat Single Sign-On 7.0
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:05:10Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.14
  creationTimestamp: null
  generation: 2
  name: redhat-sso70-openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Red Hat SSO 7.0
      iconClass: icon-sso
      openshift.io/display-name: Red Hat Single Sign-On 7.0
      supports: sso:7.0
      tags: sso,keycloak,redhat,hidden
      version: "1.3"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/redhat-sso70-openshift:1.3
    generation: 2
    importPolicy: {}
    name: "1.3"
    referencePolicy:
      type: Source
  - annotations:
      description: Red Hat SSO 7.0
      iconClass: icon-sso
      openshift.io/display-name: Red Hat Single Sign-On 7.0
      supports: sso:7.0
      tags: sso,keycloak,redhat,hidden
      version: "1.4"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/redhat-sso70-openshift:1.4
    generation: 2
    importPolicy: {}
    name: "1.4"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
