apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Redis
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:24Z
  creationTimestamp: null
  generation: 2
  name: redis
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Provides a Redis 3.2 database on RHEL 7. For more information about
        using this database image, including OpenShift considerations, see https://github.com/sclorg/redis-container/tree/master/3.2/README.md.
      iconClass: icon-redis
      openshift.io/display-name: Redis 3.2
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: redis
      version: "3.2"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/redis:3.2
    generation: 2
    importPolicy: {}
    name: "3.2"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Provides a Redis database on RHEL 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/redis-container/tree/master/3.2/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Redis available on OpenShift, including major versions updates.
      iconClass: icon-redis
      openshift.io/display-name: Redis (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: redis
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/redis:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
