apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Ruby
    openshift.io/image.dockerRepositoryCheck: 2018-09-21T12:04:18Z
  creationTimestamp: null
  generation: 2
  name: ruby
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Ruby 2.0 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-ruby-container/tree/master/2.0/README.md.
      iconClass: icon-ruby
      openshift.io/display-name: Ruby 2.0
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/ruby-ex.git
      supports: ruby:2.0,ruby
      tags: hidden,builder,ruby
      version: "2.0"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/ruby:2.0
    generation: 2
    importPolicy: {}
    name: "2.0"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run Ruby 2.2 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-ruby-container/tree/master/2.2/README.md.
      iconClass: icon-ruby
      openshift.io/display-name: Ruby 2.2
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/ruby-ex.git
      supports: ruby:2.2,ruby
      tags: builder,ruby
      version: "2.2"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/ruby:2.2
    generation: 2
    importPolicy: {}
    name: "2.2"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run Ruby 2.3 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-ruby-container/blob/master/2.3/README.md.
      iconClass: icon-ruby
      openshift.io/display-name: Ruby 2.3
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/ruby-ex.git
      supports: ruby:2.3,ruby
      tags: builder,ruby
      version: "2.3"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/ruby:2.3
    generation: 2
    importPolicy: {}
    name: "2.3"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run Ruby 2.4 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-ruby-container/blob/master/2.4/README.md.
      iconClass: icon-ruby
      openshift.io/display-name: Ruby 2.4
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/ruby-ex.git
      supports: ruby:2.4,ruby
      tags: builder,ruby
      version: "2.4"
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/ruby:2.4
    generation: 2
    importPolicy: {}
    name: "2.4"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and run Ruby applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-ruby-container/tree/master/2.3/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Ruby available on OpenShift, including major versions updates.
      iconClass: icon-ruby
      openshift.io/display-name: Ruby (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/ruby-ex.git
      supports: ruby
      tags: builder,ruby
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/openshift/ruby:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
