apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    docker-registry: default
  name: docker-registry
subsets:
- addresses:
  - ip: 10.128.0.25
    nodeName: ip-172-31-25-38.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: docker-registry-1-hh8qr
      namespace: default
      resourceVersion: "58600"
      uid: 79d0286a-bd98-11e8-89cd-0253a4143ad0
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
