apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: registry-console
    createdBy: registry-console-template
    name: registry-console
  name: registry-console
subsets:
- addresses:
  - ip: 10.129.0.29
    nodeName: ip-172-31-28-203.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: registry-console-1-qzsb9
      namespace: default
      resourceVersion: "58488"
      uid: aad398ef-bd98-11e8-89cd-0253a4143ad0
  ports:
  - name: registry-console
    port: 9090
    protocol: TCP
