apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    router: router
  name: router
subsets:
- addresses:
  - ip: 172.31.25.38
    nodeName: ip-172-31-25-38.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: router-1-97p4s
      namespace: default
      resourceVersion: "58580"
      uid: 78ac1e7b-bd98-11e8-89cd-0253a4143ad0
  ports:
  - name: 1936-tcp
    port: 1936
    protocol: TCP
  - name: 80-tcp
    port: 80
    protocol: TCP
  - name: 443-tcp
    port: 443
    protocol: TCP
