apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: webconsole-74c77977fb-
  labels:
    app: openshift-web-console
    pod-template-hash: "3073353396"
    webconsole: "true"
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: webconsole-74c77977fb
    uid: 93e21038-bd98-11e8-89cd-0253a4143ad0
spec:
  containers:
  - command:
    - /usr/bin/origin-web-console
    - --audit-log-path=-
    - -v=0
    - --config=/var/webconsole-config/webconsole-config.yaml
    image: registry.access.redhat.com/openshift3/ose-web-console:v3.9.27
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - |-
          if [[ ! -f /tmp/webconsole-config.hash ]]; then \
            md5sum /var/webconsole-config/webconsole-config.yaml > /tmp/webconsole-config.hash; \
          elif [[ $(md5sum /var/webconsole-config/webconsole-config.yaml) != $(cat /tmp/webconsole-config.hash) ]]; then \
            echo 'webconsole-config.yaml has changed.'; \
            exit 1; \
          fi && curl -k -f https://0.0.0.0:8443/console/
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: webconsole
    ports:
    - containerPort: 8443
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8443
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000080000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/serving-cert
      name: serving-cert
    - mountPath: /var/webconsole-config
      name: webconsole-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: webconsole-token-b7mk7
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: webconsole-dockercfg-m5dkv
  nodeName: ip-172-31-28-203.eu-central-1.compute.internal
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000080000
    seLinuxOptions:
      level: s0:c9,c4
  serviceAccount: webconsole
  serviceAccountName: webconsole
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: serving-cert
    secret:
      defaultMode: 288
      secretName: webconsole-serving-cert
  - configMap:
      defaultMode: 288
      name: webconsole-config
    name: webconsole-config
  - name: webconsole-token-b7mk7
    secret:
      defaultMode: 420
      secretName: webconsole-token-b7mk7
status:
  phase: Pending
  qosClass: Burstable
