apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular-metrics","name":"hawkular-metrics"},"name":"hawkular-metrics","namespace":"openshift-infra"},"spec":{"ports":[{"port":443,"targetPort":"https-endpoint"}],"selector":{"name":"hawkular-metrics"}}}
  creationTimestamp: null
  labels:
    metrics-infra: hawkular-metrics
    name: hawkular-metrics
  name: hawkular-metrics
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: https-endpoint
  selector:
    name: hawkular-metrics
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
