apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.alpha.openshift.io/serving-cert-secret-name":"heapster-certs"},"labels":{"metrics-infra":"heapster","name":"heapster"},"name":"heapster","namespace":"openshift-infra"},"spec":{"ports":[{"port":80,"targetPort":"http-endpoint"}],"selector":{"name":"heapster"}}}
    service.alpha.openshift.io/serving-cert-secret-name: heapster-certs
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1537531130
  creationTimestamp: null
  labels:
    metrics-infra: heapster
    name: heapster
  name: heapster
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-endpoint
  selector:
    name: heapster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
