apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: logging-kibana
    openshift.io/deployment.name: logging-kibana-1
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: logging-kibana-1-
  labels:
    component: kibana
    deployment: logging-kibana-1
    deploymentconfig: logging-kibana
    logging-infra: kibana
    provider: openshift
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: logging-kibana-1
    uid: 3de405cc-bd99-11e8-89cd-0253a4143ad0
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: logging-infra
              operator: In
              values:
              - kibana
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - env:
    - name: ES_HOST
      value: logging-es
    - name: ES_PORT
      value: "9200"
    - name: KIBANA_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: kibana
          divisor: "0"
          resource: limits.memory
    image: registry.access.redhat.com/openshift3/logging-kibana:v3.9.27
    imagePullPolicy: IfNotPresent
    name: kibana
    readinessProbe:
      exec:
        command:
        - /usr/share/kibana/probe/readiness.sh
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4
    resources:
      limits:
        memory: 736Mi
      requests:
        cpu: 100m
        memory: 736Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000070000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kibana/keys
      name: kibana
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: aggregated-logging-kibana-token-4n6gs
      readOnly: true
  - env:
    - name: OAP_BACKEND_URL
      value: http://localhost:5601
    - name: OAP_AUTH_MODE
      value: oauth2
    - name: OAP_TRANSFORM
      value: user_header,token_header
    - name: OAP_OAUTH_ID
      value: kibana-proxy
    - name: OAP_MASTER_URL
      value: https://kubernetes.default.svc.cluster.local
    - name: OAP_PUBLIC_MASTER_URL
      value: https://backupmaster008.amosdemo.io:8443
    - name: OAP_LOGOUT_REDIRECT
      value: https://backupmaster008.amosdemo.io:8443/console/logout
    - name: OAP_MASTER_CA_FILE
      value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - name: OAP_DEBUG
      value: "False"
    - name: OAP_OAUTH_SECRET_FILE
      value: /secret/oauth-secret
    - name: OAP_SERVER_CERT_FILE
      value: /secret/server-cert
    - name: OAP_SERVER_KEY_FILE
      value: /secret/server-key
    - name: OAP_SERVER_TLS_FILE
      value: /secret/server-tls.json
    - name: OAP_SESSION_SECRET_FILE
      value: /secret/session-secret
    - name: OCP_AUTH_PROXY_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: kibana-proxy
          divisor: "0"
          resource: limits.memory
    image: registry.access.redhat.com/openshift3/logging-auth-proxy:v3.9.27
    imagePullPolicy: IfNotPresent
    name: kibana-proxy
    ports:
    - containerPort: 3000
      name: oaproxy
      protocol: TCP
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000070000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /secret
      name: kibana-proxy
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: aggregated-logging-kibana-token-4n6gs
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: aggregated-logging-kibana-dockercfg-wkmkc
  nodeName: ip-172-31-28-203.eu-central-1.compute.internal
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000070000
    seLinuxOptions:
      level: s0:c8,c7
  serviceAccount: aggregated-logging-kibana
  serviceAccountName: aggregated-logging-kibana
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kibana
    secret:
      defaultMode: 420
      secretName: logging-kibana
  - name: kibana-proxy
    secret:
      defaultMode: 420
      secretName: logging-kibana-proxy
  - name: aggregated-logging-kibana-token-4n6gs
    secret:
      defaultMode: 420
      secretName: aggregated-logging-kibana-token-4n6gs
status:
  phase: Pending
  qosClass: Burstable
