apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system::leader-locking-kube-controller-manager
roleRef:
  name: system::leader-locking-kube-controller-manager
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kube-controller-manager
  namespace: kube-system
userNames:
- system:serviceaccount:kube-system:kube-controller-manager
