apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:cloud-provider
roleRef:
  name: system:controller:cloud-provider
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cloud-provider
  namespace: kube-system
userNames:
- system:serviceaccount:kube-system:cloud-provider
