apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  name: alerts
spec:
  host: alerts-openshift-metrics.apps008.amosdemo.io
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: alerts
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-09-21T12:25:39Z
      status: "True"
      type: Admitted
    host: alerts-openshift-metrics.apps008.amosdemo.io
    routerName: router
    wildcardPolicy: None
