apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  name: alertmanager
spec:
  host: alertmanager-openshift-metrics.apps008.amosdemo.io
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: alertmanager
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-09-21T12:25:41Z
      status: "True"
      type: Admitted
    host: alertmanager-openshift-metrics.apps008.amosdemo.io
    routerName: router
    wildcardPolicy: None
