apiVersion: v1
kind: Role
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: prometheus-metrics-viewer
rules:
- apiGroups:
  - metrics.openshift.io
  attributeRestrictions: null
  resources:
  - prometheus
  verbs:
  - view
