apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: registry-console
    openshift.io/deployment.name: registry-console-1
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: registry-console-1-
  labels:
    app: registry-console
    deployment: registry-console-1
    deploymentconfig: registry-console
    name: registry-console
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: registry-console-1
    uid: 8ec9b263-bd98-11e8-89cd-0253a4143ad0
spec:
  containers:
  - env:
    - name: OPENSHIFT_OAUTH_PROVIDER_URL
      value: https://backupmaster008.amosdemo.io:8443
    - name: OPENSHIFT_OAUTH_CLIENT_ID
      value: cockpit-oauth-client
    - name: KUBERNETES_INSECURE
      value: "false"
    - name: COCKPIT_KUBE_INSECURE
      value: "false"
    - name: REGISTRY_ONLY
      value: "true"
    - name: REGISTRY_HOST
      value: docker-registry-default.apps008.amosdemo.io
    image: registry.access.redhat.com/openshift3/registry-console:v3.9
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /ping
        port: 9090
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: registry-console
    ports:
    - containerPort: 9090
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ping
        port: 9090
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000000000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2b62h
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-hj5gz
  nodeName: ip-172-31-28-203.eu-central-1.compute.internal
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000000000
    seLinuxOptions:
      level: s0:c1,c0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-2b62h
    secret:
      defaultMode: 420
      secretName: default-token-2b62h
status:
  phase: Pending
  qosClass: BestEffort
