apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"openshift-web-console"},"name":"webconsole","namespace":"openshift-web-console"}}
  creationTimestamp: null
  labels:
    app: openshift-web-console
  name: webconsole
