apiVersion: v1
kind: Role
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: extension-apiserver-authentication-reader
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
