apiVersion: v1
kind: Role
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system::leader-locking-kube-scheduler
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  verbs:
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resourceNames:
  - kube-scheduler
  resources:
  - configmaps
  verbs:
  - get
  - update
