apiVersion: v1
groupNames:
- system:authenticated
kind: RoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: shared-resource-viewers
roleRef:
  name: shared-resource-viewer
  namespace: openshift
subjects:
- kind: SystemGroup
  name: system:authenticated
userNames: null
