apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: openshift-web-console
  name: webconsole
subsets:
- addresses:
  - ip: 10.129.0.31
    nodeName: ip-172-31-28-203.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: webconsole-74c77977fb-w6l5s
      namespace: openshift-web-console
      resourceVersion: "58484"
      uid: 947ef424-bd98-11e8-89cd-0253a4143ad0
  ports:
  - name: https
    port: 8443
    protocol: TCP
