apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: logging-elasticsearch-view-role
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: aggregated-logging-elasticsearch
  namespace: logging
userNames:
- system:serviceaccount:logging:aggregated-logging-elasticsearch
