apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular"},"name":"hawkular-view","namespace":"openshift-infra"},"roleRef":{"name":"view"},"subjects":[{"kind":"ServiceAccount","name":"hawkular"}]}
  creationTimestamp: null
  labels:
    metrics-infra: hawkular
  name: hawkular-view
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: hawkular
  namespace: openshift-infra
userNames:
- system:serviceaccount:openshift-infra:hawkular
