apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /_prometheus/metrics
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-tls
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1537531130
  creationTimestamp: null
  labels:
    logging-infra: support
  name: logging-es-prometheus
spec:
  ports:
  - name: proxy
    port: 443
    protocol: TCP
    targetPort: 4443
  selector:
    component: es
    provider: openshift
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
