apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    logging-infra: support
  name: logging-es
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: restapi
  selector:
    component: es
    provider: openshift
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
