apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    logging-infra: support
  name: logging-kibana
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: oaproxy
  selector:
    component: kibana
    provider: openshift
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
