apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c8,c7
    openshift.io/sa.scc.supplemental-groups: 1000070000/10000
    openshift.io/sa.scc.uid-range: 1000070000/10000
    quota.openshift.io/cluster-resource-override-enabled: "false"
  creationTimestamp: null
  name: logging
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
