apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: dancer-mysql-example
    template: dancer-mysql-example
  name: dancer-mysql-example
subsets:
- addresses:
  - ip: 10.130.0.225
    nodeName: ip-172-31-73-81.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: dancer-mysql-example-1-bgbkc
      namespace: demoproject
      resourceVersion: "342261"
      uid: f220b399-c15e-11e8-9d6d-0253a4143ad0
  ports:
  - name: web
    port: 8080
    protocol: TCP
