apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: dancer-mysql-example
    template: dancer-mysql-example
  name: database
subsets:
- addresses:
  - ip: 10.130.0.223
    nodeName: ip-172-31-73-81.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: database-1-6fslq
      namespace: demoproject
      resourceVersion: "341988"
      uid: 9c243fa9-c15e-11e8-9d6d-0253a4143ad0
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
