apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    logging-infra: support
  name: logging-kibana
subsets:
- addresses:
  - ip: 10.129.0.34
    nodeName: ip-172-31-28-203.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: logging-kibana-1-snbx6
      namespace: logging
      resourceVersion: "58566"
      uid: 3f355b81-bd99-11e8-89cd-0253a4143ad0
  ports:
  - port: 3000
    protocol: TCP
