apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  creationTimestamp: null
  labels:
    app: dancer-mysql-example
    template: dancer-mysql-example
  name: dancer-mysql-example
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: dancer-mysql-example:latest
  postCommit:
    script: perl -I extlib/lib/perl5 -I lib t/*
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/openshift/dancer-ex.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: CPAN_MIRROR
      from:
        kind: ImageStreamTag
        name: perl:5.24
        namespace: openshift
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
  - github:
      secret: MSFVRF26snT3CXjx7IPKfXsFt4EueobSo52aPtnw
    type: GitHub
status:
  lastVersion: 0
