apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: admin-0
roleRef:
  name: admin
subjects:
- kind: ServiceAccount
  name: management-admin
  namespace: management-infra
userNames:
- system:serviceaccount:management-infra:management-admin
