apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: admin
roleRef:
  name: admin
subjects:
- kind: User
  name: management-admin
userNames:
- management-admin
