apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/build.name: dancer-mysql-example-1
    openshift.io/scc: privileged
  creationTimestamp: null
  labels:
    openshift.io/build.name: dancer-mysql-example-1
  name: dancer-mysql-example-1-build
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: dancer-mysql-example-1
    uid: 99e5161f-c15e-11e8-9d6d-0253a4143ad0
spec:
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"dancer-mysql-example-1","namespace":"demoproject","selfLink":"/apis/build.openshift.io/v1/namespaces/demoproject/builds/dancer-mysql-example-1","uid":"99e5161f-c15e-11e8-9d6d-0253a4143ad0","resourceVersion":"341898","creationTimestamp":"2018-09-26T07:34:28Z","labels":{"app":"dancer-mysql-example","buildconfig":"dancer-mysql-example","openshift.io/build-config.name":"dancer-mysql-example","openshift.io/build.start-policy":"Serial","template":"dancer-mysql-example"},"annotations":{"openshift.io/build-config.name":"dancer-mysql-example","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"dancer-mysql-example","uid":"99e0746b-c15e-11e8-9d6d-0253a4143ad0","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/dancer-ex.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/rhscl/perl-524-rhel7@sha256:bdecfc378b94066c6ec1d0a3d7f1828b71b6e1caf0b67aecdc6b50ca81f76c09"},"env":[{"name":"CPAN_MIRROR"}]}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/demoproject/dancer-mysql-example:latest"},"pushSecret":{"name":"builder-dockercfg-n657n"}},"resources":{},"postCommit":{"script":"perl -I extlib/lib/perl5 -I lib t/*"},"nodeSelector":null,"triggeredBy":[{"message":"Build configuration change"}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/demoproject/dancer-mysql-example:latest","config":{"kind":"BuildConfig","namespace":"demoproject","name":"dancer-mysql-example"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/openshift/dancer-ex.git
    - name: SOURCE_URI
      value: https://github.com/openshift/dancer-ex.git
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    image: registry.access.redhat.com/openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/docker.sock
      name: docker-socket
    - mountPath: /var/run/crio/crio.sock
      name: crio-socket
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-n657n-push
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-fbd55
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: builder-dockercfg-n657n
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-git-clone
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"dancer-mysql-example-1","namespace":"demoproject","selfLink":"/apis/build.openshift.io/v1/namespaces/demoproject/builds/dancer-mysql-example-1","uid":"99e5161f-c15e-11e8-9d6d-0253a4143ad0","resourceVersion":"341898","creationTimestamp":"2018-09-26T07:34:28Z","labels":{"app":"dancer-mysql-example","buildconfig":"dancer-mysql-example","openshift.io/build-config.name":"dancer-mysql-example","openshift.io/build.start-policy":"Serial","template":"dancer-mysql-example"},"annotations":{"openshift.io/build-config.name":"dancer-mysql-example","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"dancer-mysql-example","uid":"99e0746b-c15e-11e8-9d6d-0253a4143ad0","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/dancer-ex.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/rhscl/perl-524-rhel7@sha256:bdecfc378b94066c6ec1d0a3d7f1828b71b6e1caf0b67aecdc6b50ca81f76c09"},"env":[{"name":"CPAN_MIRROR"}]}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/demoproject/dancer-mysql-example:latest"},"pushSecret":{"name":"builder-dockercfg-n657n"}},"resources":{},"postCommit":{"script":"perl -I extlib/lib/perl5 -I lib t/*"},"nodeSelector":null,"triggeredBy":[{"message":"Build configuration change"}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/demoproject/dancer-mysql-example:latest","config":{"kind":"BuildConfig","namespace":"demoproject","name":"dancer-mysql-example"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/openshift/dancer-ex.git
    - name: SOURCE_URI
      value: https://github.com/openshift/dancer-ex.git
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: registry.access.redhat.com/openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-fbd55
      readOnly: true
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"dancer-mysql-example-1","namespace":"demoproject","selfLink":"/apis/build.openshift.io/v1/namespaces/demoproject/builds/dancer-mysql-example-1","uid":"99e5161f-c15e-11e8-9d6d-0253a4143ad0","resourceVersion":"341898","creationTimestamp":"2018-09-26T07:34:28Z","labels":{"app":"dancer-mysql-example","buildconfig":"dancer-mysql-example","openshift.io/build-config.name":"dancer-mysql-example","openshift.io/build.start-policy":"Serial","template":"dancer-mysql-example"},"annotations":{"openshift.io/build-config.name":"dancer-mysql-example","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"dancer-mysql-example","uid":"99e0746b-c15e-11e8-9d6d-0253a4143ad0","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/dancer-ex.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/rhscl/perl-524-rhel7@sha256:bdecfc378b94066c6ec1d0a3d7f1828b71b6e1caf0b67aecdc6b50ca81f76c09"},"env":[{"name":"CPAN_MIRROR"}]}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/demoproject/dancer-mysql-example:latest"},"pushSecret":{"name":"builder-dockercfg-n657n"}},"resources":{},"postCommit":{"script":"perl -I extlib/lib/perl5 -I lib t/*"},"nodeSelector":null,"triggeredBy":[{"message":"Build configuration change"}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/demoproject/dancer-mysql-example:latest","config":{"kind":"BuildConfig","namespace":"demoproject","name":"dancer-mysql-example"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/openshift/dancer-ex.git
    - name: SOURCE_URI
      value: https://github.com/openshift/dancer-ex.git
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: registry.access.redhat.com/openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-fbd55
      readOnly: true
  nodeName: ip-172-31-73-81.eu-central-1.compute.internal
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: buildworkdir
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker-socket
  - hostPath:
      path: /var/run/crio/crio.sock
      type: ""
    name: crio-socket
  - name: builder-dockercfg-n657n-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-n657n
  - name: builder-token-fbd55
    secret:
      defaultMode: 420
      secretName: builder-token-fbd55
status:
  phase: Pending
  qosClass: BestEffort
