apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  creationTimestamp: null
  labels:
    app: dancer-mysql-example
    template: dancer-mysql-example
  name: database
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
