apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-09-21 12:24:43 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-09-21 12:24:31 +0000 UTC
    openshift.io/deployer-pod.name: logging-curator-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: logging-curator
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"logging-curator","namespace":"logging","selfLink":"/apis/apps.openshift.io/v1/namespaces/logging/deploymentconfigs/logging-curator","uid":"4acf2654-bd99-11e8-89cd-0253a4143ad0","resourceVersion":"3957","generation":1,"creationTimestamp":"2018-09-21T12:24:31Z","labels":{"component":"curator","logging-infra":"curator","provider":"openshift"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"component":"curator","logging-infra":"curator","provider":"openshift"},"template":{"metadata":{"name":"logging-curator","creationTimestamp":null,"labels":{"component":"curator","logging-infra":"curator","provider":"openshift"}},"spec":{"volumes":[{"name":"certs","secret":{"secretName":"logging-curator","defaultMode":420}},{"name":"config","configMap":{"name":"logging-curator","defaultMode":420}}],"containers":[{"name":"curator","image":"registry.access.redhat.com/openshift3/logging-curator:v3.9.27","env":[{"name":"K8S_HOST_URL","value":"https://kubernetes.default.svc.cluster.local"},{"name":"ES_HOST","value":"logging-es"},{"name":"ES_PORT","value":"9200"},{"name":"ES_CLIENT_CERT","value":"/etc/curator/keys/cert"},{"name":"ES_CLIENT_KEY","value":"/etc/curator/keys/key"},{"name":"ES_CA","value":"/etc/curator/keys/ca"},{"name":"CURATOR_DEFAULT_DAYS","value":"30"},{"name":"CURATOR_RUN_HOUR","value":"3"},{"name":"CURATOR_RUN_MINUTE","value":"30"},{"name":"CURATOR_RUN_TIMEZONE","value":"UTC"},{"name":"CURATOR_SCRIPT_LOG_LEVEL","value":"INFO"},{"name":"CURATOR_LOG_LEVEL","value":"ERROR"}],"resources":{"limits":{"memory":"256Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"name":"certs","readOnly":true,"mountPath":"/etc/curator/keys"},{"name":"config","readOnly":true,"mountPath":"/etc/curator/settings"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"aggregated-logging-curator","serviceAccount":"aggregated-logging-curator","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":0,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: curator
    logging-infra: curator
    openshift.io/deployment-config.name: logging-curator
    provider: openshift
  name: logging-curator-1
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: logging-curator
    uid: 4acf2654-bd99-11e8-89cd-0253a4143ad0
spec:
  replicas: 1
  selector:
    component: curator
    deployment: logging-curator-1
    deploymentconfig: logging-curator
    logging-infra: curator
    provider: openshift
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: logging-curator
        openshift.io/deployment.name: logging-curator-1
      creationTimestamp: null
      labels:
        component: curator
        deployment: logging-curator-1
        deploymentconfig: logging-curator
        logging-infra: curator
        provider: openshift
    spec:
      containers:
      - env:
        - name: K8S_HOST_URL
          value: https://kubernetes.default.svc.cluster.local
        - name: ES_HOST
          value: logging-es
        - name: ES_PORT
          value: "9200"
        - name: ES_CLIENT_CERT
          value: /etc/curator/keys/cert
        - name: ES_CLIENT_KEY
          value: /etc/curator/keys/key
        - name: ES_CA
          value: /etc/curator/keys/ca
        - name: CURATOR_DEFAULT_DAYS
          value: "30"
        - name: CURATOR_RUN_HOUR
          value: "3"
        - name: CURATOR_RUN_MINUTE
          value: "30"
        - name: CURATOR_RUN_TIMEZONE
          value: UTC
        - name: CURATOR_SCRIPT_LOG_LEVEL
          value: INFO
        - name: CURATOR_LOG_LEVEL
          value: ERROR
        image: registry.access.redhat.com/openshift3/logging-curator:v3.9.27
        imagePullPolicy: IfNotPresent
        name: curator
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/curator/keys
          name: certs
          readOnly: true
        - mountPath: /etc/curator/settings
          name: config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aggregated-logging-curator
      serviceAccountName: aggregated-logging-curator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: logging-curator
      - configMap:
          defaultMode: 420
          name: logging-curator
        name: config
status:
  replicas: 0
