apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2018-09-21 12:35:19 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-09-21 12:25:16 +0000 UTC
    openshift.io/deployer-pod.name: logging-es-data-master-vvco3d6k-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: logging-es-data-master-vvco3d6k
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: manual change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"logging-es-data-master-vvco3d6k","namespace":"logging","selfLink":"/apis/apps.openshift.io/v1/namespaces/logging/deploymentconfigs/logging-es-data-master-vvco3d6k","uid":"2f454aae-bd99-11e8-89cd-0253a4143ad0","resourceVersion":"4197","generation":2,"creationTimestamp":"2018-09-21T12:23:45Z","labels":{"component":"es","deployment":"logging-es-data-master-vvco3d6k","logging-infra":"elasticsearch","provider":"openshift"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[],"replicas":1,"revisionHistoryLimit":0,"test":false,"selector":{"component":"es","deployment":"logging-es-data-master-vvco3d6k","logging-infra":"elasticsearch","provider":"openshift"},"template":{"metadata":{"name":"logging-es-data-master-vvco3d6k","creationTimestamp":null,"labels":{"component":"es","deployment":"logging-es-data-master-vvco3d6k","logging-infra":"elasticsearch","provider":"openshift"}},"spec":{"volumes":[{"name":"proxy-tls","secret":{"secretName":"prometheus-tls","defaultMode":420}},{"name":"elasticsearch","secret":{"secretName":"logging-elasticsearch","defaultMode":420}},{"name":"elasticsearch-config","configMap":{"name":"logging-elasticsearch","defaultMode":420}},{"name":"elasticsearch-storage","persistentVolumeClaim":{"claimName":"logging-es-0"}}],"containers":[{"name":"elasticsearch","image":"registry.access.redhat.com/openshift3/logging-elasticsearch:v3.9.27","ports":[{"name":"restapi","containerPort":9200,"protocol":"TCP"},{"name":"cluster","containerPort":9300,"protocol":"TCP"}],"env":[{"name":"DC_NAME","value":"logging-es-data-master-vvco3d6k"},{"name":"NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"KUBERNETES_TRUST_CERT","value":"true"},{"name":"SERVICE_DNS","value":"logging-es-cluster"},{"name":"CLUSTER_NAME","value":"logging-es"},{"name":"INSTANCE_RAM","value":"8Gi"},{"name":"HEAP_DUMP_LOCATION","value":"/elasticsearch/persistent/heapdump.hprof"},{"name":"NODE_QUORUM","value":"1"},{"name":"RECOVER_EXPECTED_NODES","value":"1"},{"name":"RECOVER_AFTER_TIME","value":"5m"},{"name":"READINESS_PROBE_TIMEOUT","value":"30"},{"name":"POD_LABEL","value":"component=es"},{"name":"IS_MASTER","value":"true"},{"name":"HAS_DATA","value":"true"},{"name":"PROMETHEUS_USER","value":"system:serviceaccount:openshift-metrics:prometheus"}],"resources":{"limits":{"memory":"8Gi"},"requests":{"cpu":"1","memory":"8Gi"}},"volumeMounts":[{"name":"elasticsearch","readOnly":true,"mountPath":"/etc/elasticsearch/secret"},{"name":"elasticsearch-config","readOnly":true,"mountPath":"/usr/share/java/elasticsearch/config"},{"name":"elasticsearch-storage","mountPath":"/elasticsearch/persistent"}],"readinessProbe":{"exec":{"command":["/usr/share/java/elasticsearch/probe/readiness.sh"]},"initialDelaySeconds":10,"timeoutSeconds":30,"periodSeconds":5,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"},{"name":"proxy","image":"registry.access.redhat.com/openshift3/oauth-proxy:v3.9.27","args":["--upstream-ca=/etc/elasticsearch/secret/admin-ca","--https-address=:4443","-provider=openshift","-client-id=system:serviceaccount:logging:aggregated-logging-elasticsearch","-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token","-cookie-secret=aHRLTkJyTEE2NldWdVBCSA==","-basic-auth-password=fc8Rnlb39LJzufVr","-upstream=https://localhost:9200","-openshift-sar={\"namespace\": \"logging\", \"verb\": \"view\", \"resource\": \"prometheus\", \"group\": \"metrics.openshift.io\"}","-openshift-delegate-urls={\"/\": {\"resource\": \"prometheus\", \"verb\": \"view\", \"group\": \"metrics.openshift.io\", \"namespace\": \"logging\"}}","--tls-cert=/etc/tls/private/tls.crt","--tls-key=/etc/tls/private/tls.key","-pass-access-token","-pass-user-headers"],"ports":[{"name":"proxy","containerPort":4443,"protocol":"TCP"}],"resources":{"limits":{"memory":"64Mi"},"requests":{"cpu":"100m","memory":"64Mi"}},"volumeMounts":[{"name":"proxy-tls","readOnly":true,"mountPath":"/etc/tls/private"},{"name":"elasticsearch","readOnly":true,"mountPath":"/etc/elasticsearch/secret"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"aggregated-logging-elasticsearch","serviceAccount":"aggregated-logging-elasticsearch","securityContext":{"supplementalGroups":[65534]},"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"logging-infra","operator":"In","values":["elasticsearch"]}]},"topologyKey":"kubernetes.io/hostname"}}]}},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"manual change","causes":[{"type":"Manual"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-09-21T12:23:45Z","lastTransitionTime":"2018-09-21T12:23:45Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: null
  generation: 1
  labels:
    component: es
    deployment: logging-es-data-master-vvco3d6k
    logging-infra: elasticsearch
    openshift.io/deployment-config.name: logging-es-data-master-vvco3d6k
    provider: openshift
  name: logging-es-data-master-vvco3d6k-1
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: logging-es-data-master-vvco3d6k
    uid: 2f454aae-bd99-11e8-89cd-0253a4143ad0
spec:
  replicas: 0
  selector:
    component: es
    deployment: logging-es-data-master-vvco3d6k-1
    deploymentconfig: logging-es-data-master-vvco3d6k
    logging-infra: elasticsearch
    provider: openshift
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: logging-es-data-master-vvco3d6k
        openshift.io/deployment.name: logging-es-data-master-vvco3d6k-1
      creationTimestamp: null
      labels:
        component: es
        deployment: logging-es-data-master-vvco3d6k-1
        deploymentconfig: logging-es-data-master-vvco3d6k
        logging-infra: elasticsearch
        provider: openshift
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: logging-infra
                  operator: In
                  values:
                  - elasticsearch
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: DC_NAME
          value: logging-es-data-master-vvco3d6k
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: SERVICE_DNS
          value: logging-es-cluster
        - name: CLUSTER_NAME
          value: logging-es
        - name: INSTANCE_RAM
          value: 8Gi
        - name: HEAP_DUMP_LOCATION
          value: /elasticsearch/persistent/heapdump.hprof
        - name: NODE_QUORUM
          value: "1"
        - name: RECOVER_EXPECTED_NODES
          value: "1"
        - name: RECOVER_AFTER_TIME
          value: 5m
        - name: READINESS_PROBE_TIMEOUT
          value: "30"
        - name: POD_LABEL
          value: component=es
        - name: IS_MASTER
          value: "true"
        - name: HAS_DATA
          value: "true"
        - name: PROMETHEUS_USER
          value: system:serviceaccount:openshift-metrics:prometheus
        image: registry.access.redhat.com/openshift3/logging-elasticsearch:v3.9.27
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: restapi
          protocol: TCP
        - containerPort: 9300
          name: cluster
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/share/java/elasticsearch/probe/readiness.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/elasticsearch/secret
          name: elasticsearch
          readOnly: true
        - mountPath: /usr/share/java/elasticsearch/config
          name: elasticsearch-config
          readOnly: true
        - mountPath: /elasticsearch/persistent
          name: elasticsearch-storage
      - args:
        - --upstream-ca=/etc/elasticsearch/secret/admin-ca
        - --https-address=:4443
        - -provider=openshift
        - -client-id=system:serviceaccount:logging:aggregated-logging-elasticsearch
        - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -cookie-secret=aHRLTkJyTEE2NldWdVBCSA==
        - -basic-auth-password=fc8Rnlb39LJzufVr
        - -upstream=https://localhost:9200
        - '-openshift-sar={"namespace": "logging", "verb": "view", "resource": "prometheus",
          "group": "metrics.openshift.io"}'
        - '-openshift-delegate-urls={"/": {"resource": "prometheus", "verb": "view",
          "group": "metrics.openshift.io", "namespace": "logging"}}'
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - -pass-access-token
        - -pass-user-headers
        image: registry.access.redhat.com/openshift3/oauth-proxy:v3.9.27
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 4443
          name: proxy
          protocol: TCP
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls
          readOnly: true
        - mountPath: /etc/elasticsearch/secret
          name: elasticsearch
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 65534
      serviceAccount: aggregated-logging-elasticsearch
      serviceAccountName: aggregated-logging-elasticsearch
      terminationGracePeriodSeconds: 30
      volumes:
      - name: proxy-tls
        secret:
          defaultMode: 420
          secretName: prometheus-tls
      - name: elasticsearch
        secret:
          defaultMode: 420
          secretName: logging-elasticsearch
      - configMap:
          defaultMode: 420
          name: logging-elasticsearch
        name: elasticsearch-config
      - name: elasticsearch-storage
        persistentVolumeClaim:
          claimName: logging-es-0
status:
  replicas: 0
