apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: cluster-debugger
rules:
- apiGroups: null
  attributeRestrictions: null
  nonResourceURLs:
  - /debug/pprof
  - /debug/pprof/*
  - /metrics
  resources: []
  verbs:
  - get
