apiVersion: v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    metrics-infra: hawkular-metrics
  name: hawkular-metrics
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
