apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:image-signer
rules:
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - images
  - imagestreams/layers
  verbs:
  - get
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagesignatures
  verbs:
  - create
  - delete
