apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:oauth-token-deleter
rules:
- apiGroups:
  - ""
  - oauth.openshift.io
  attributeRestrictions: null
  resources:
  - oauthaccesstokens
  - oauthauthorizetokens
  verbs:
  - delete
