apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:horizontal-pod-autoscaler
rules:
- apiGroups:
  - autoscaling
  attributeRestrictions: null
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  attributeRestrictions: null
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - update
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - '*/scale'
  verbs:
  - get
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resourceNames:
  - 'http:heapster:'
  - 'https:heapster:'
  resources:
  - services/proxy
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - custom.metrics.k8s.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - create
  - patch
  - update
