apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:openshift:templateservicebroker-client
rules:
- apiGroups: null
  attributeRestrictions: null
  nonResourceURLs:
  - /brokers/template.openshift.io/*
  resources: []
  verbs:
  - delete
  - get
  - put
  - update
