apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:openshift:controller:image-trigger-controller
rules:
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreams
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - daemonsets
  verbs:
  - get
  - update
- apiGroups:
  - apps
  - extensions
  attributeRestrictions: null
  resources:
  - deployments
  verbs:
  - get
  - update
- apiGroups:
  - apps
  attributeRestrictions: null
  resources:
  - statefulsets
  verbs:
  - get
  - update
- apiGroups:
  - batch
  attributeRestrictions: null
  resources:
  - cronjobs
  verbs:
  - get
  - update
- apiGroups:
  - ""
  - apps.openshift.io
  attributeRestrictions: null
  resources:
  - deploymentconfigs
  verbs:
  - get
  - update
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - buildconfigs/instantiate
  verbs:
  - create
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - builds/custom
  - builds/docker
  - builds/jenkinspipeline
  - builds/optimizeddocker
  - builds/source
  verbs:
  - create
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - create
  - patch
  - update
