apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:openshift:controller:template-service-broker
rules:
- apiGroups:
  - authorization.k8s.io
  attributeRestrictions: null
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - authorization.openshift.io
  attributeRestrictions: null
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - template.openshift.io
  attributeRestrictions: null
  resources:
  - brokertemplateinstances
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - template.openshift.io
  attributeRestrictions: null
  resources:
  - brokertemplateinstances/finalizers
  verbs:
  - update
- apiGroups:
  - template.openshift.io
  attributeRestrictions: null
  resources:
  - templateinstances
  verbs:
  - assign
  - create
  - delete
  - get
- apiGroups:
  - template.openshift.io
  attributeRestrictions: null
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - services
  verbs:
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
- apiGroups:
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - create
  - patch
  - update
