apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:image-auditor
rules:
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - images
  verbs:
  - get
  - list
  - patch
  - update
  - watch
