apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:node-proxier
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
