apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Grants the right to pull images from within a project.
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:image-puller
rules:
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreams/layers
  verbs:
  - get
