apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:scope-impersonation
rules:
- apiGroups:
  - authentication.k8s.io
  attributeRestrictions: null
  resources:
  - userextras/scopes.authorization.openshift.io
  verbs:
  - impersonate
