apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  creationTimestamp: null
  name: system:image-pruner
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  - replicationcontrollers
  verbs:
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - limitranges
  verbs:
  - list
- apiGroups:
  - ""
  - build.openshift.io
  attributeRestrictions: null
  resources:
  - buildconfigs
  - builds
  verbs:
  - get
  - list
- apiGroups:
  - ""
  - apps.openshift.io
  attributeRestrictions: null
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
- apiGroups:
  - apps
  - extensions
  attributeRestrictions: null
  resources:
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - apps
  - extensions
  attributeRestrictions: null
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - apps
  - extensions
  attributeRestrictions: null
  resources:
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - images
  verbs:
  - delete
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - images
  - imagestreams
  verbs:
  - get
  - list
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreams/status
  verbs:
  - update
