apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    metrics-infra: hawkular-metrics
    name: hawkular-metrics
  name: hawkular-metrics
subsets:
- addresses:
  - ip: 10.129.0.30
    nodeName: ip-172-31-28-203.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: hawkular-metrics-hcdwp
      namespace: openshift-infra
      resourceVersion: "58646"
      uid: f1c7cdea-bd98-11e8-89cd-0253a4143ad0
  ports:
  - port: 8443
    protocol: TCP
