apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    metrics-infra: heapster
    name: heapster
  name: heapster
subsets:
- addresses:
  - ip: 10.129.0.33
    nodeName: ip-172-31-28-203.eu-central-1.compute.internal
    targetRef:
      kind: Pod
      name: heapster-x5dhc
      namespace: openshift-infra
      resourceVersion: "58655"
      uid: f2f9f4d4-bd98-11e8-89cd-0253a4143ad0
  ports:
  - port: 8082
    protocol: TCP
