apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: heapster-
  labels:
    metrics-infra: heapster
    name: heapster
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: heapster
    uid: df697413-bd98-11e8-89cd-0253a4143ad0
spec:
  containers:
  - command:
    - heapster-wrapper.sh
    - --wrapper.allowed_users_file=/secrets/heapster.allowed-users
    - --source=kubernetes.summary_api:${MASTER_URL}?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
    - --tls_cert=/heapster-certs/tls.crt
    - --tls_key=/heapster-certs/tls.key
    - --tls_client_ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - --allowed_users=%allowed_users%
    - --metric_resolution=30s
    - --wrapper.username_file=/hawkular-account/hawkular-metrics.username
    - --wrapper.password_file=/hawkular-account/hawkular-metrics.password
    - --wrapper.endpoint_check=https://hawkular-metrics:443/hawkular/metrics/status
    - --sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-metrics-certs/tls.crt&user=%username%&pass=%password%&filter=label(container_name:^system.slice.*|^user.slice)&concurrencyLimit=5
    env:
    - name: STARTUP_TIMEOUT
      value: "500"
    image: registry.access.redhat.com/openshift3/metrics-heapster:v3.9.27
    imagePullPolicy: IfNotPresent
    name: heapster
    ports:
    - containerPort: 8082
      name: http-endpoint
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /opt/heapster-readiness.sh
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 3750M
      requests:
        memory: 937500k
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000040000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /secrets
      name: heapster-secrets
    - mountPath: /heapster-certs
      name: heapster-certs
    - mountPath: /hawkular-metrics-certs
      name: hawkular-metrics-certs
    - mountPath: /hawkular-account
      name: hawkular-metrics-account
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: heapster-token-rffqz
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: heapster-dockercfg-s7g7d
  nodeName: ip-172-31-28-203.eu-central-1.compute.internal
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000040000
    seLinuxOptions:
      level: s0:c6,c5
  serviceAccount: heapster
  serviceAccountName: heapster
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: heapster-secrets
    secret:
      defaultMode: 420
      secretName: heapster-secrets
  - name: heapster-certs
    secret:
      defaultMode: 420
      secretName: heapster-certs
  - name: hawkular-metrics-certs
    secret:
      defaultMode: 420
      secretName: hawkular-metrics-certs
  - name: hawkular-metrics-account
    secret:
      defaultMode: 420
      secretName: hawkular-metrics-account
  - name: heapster-token-rffqz
    secret:
      defaultMode: 420
      secretName: heapster-token-rffqz
status:
  phase: Pending
  qosClass: Burstable
